name: Suggestion
description: Suggest a change or addition.
title: "[SUGGESTION]: "
labels: ["enhancement"]
assignees:
  - DVOA1

body:
  - type: markdown
    attributes:
      value: |
        ## Pointers before submitting a suggestion:
        - Check for similar suggestions in the **Issues** section.

  - type: textarea
    id: description
    attributes:
      label: Describe your suggestion
      description: What would you like added or changed?
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Why should this be added or changed?
      description: Let us know the reasoning behind your suggestion.
    validations:
      required: true

  - type: dropdown
    id: is_based_on_issue
    attributes:
      label: Is this suggestion based on a known issue?
      options:
        - "Yes"
        - "No"
    validations:
      required: false